# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('keep_list', models.CharField(blank=True, max_length=255, null=True)),
                ('waters', models.BooleanField(default=False)),
                ('three_d', models.BooleanField(default=False)),
                ('combi', models.BooleanField(default=False)),
                ('multiple', models.BooleanField(default=False)),
                ('confs', models.IntegerField(blank=True, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
                ('step', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('dstep', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('res', models.CommaSeparatedIntegerField(blank=True, max_length=15, null=True)),
                ('modes', models.CommaSeparatedIntegerField(blank=True, max_length=50, null=True)),
                ('ecuts', models.CharField(blank=True, max_length=50, null=True)),
                ('video_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
