# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdrop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='video_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
