# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdrop', '0002_auto_20170520_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='video_text',
            new_name='video_path',
        ),
    ]
