# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 22:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pdbdrop', '0003_auto_20170520_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='modes',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='res',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='three_d',
            field=models.BooleanField(default=False, verbose_name='3D'),
        ),
    ]
